=== digital-asset/daml/sdk/type-json/typesig.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/$defs/PackageSignature",
  "title": "Package Signature",
  "description": "Package Signature",
  "$defs": {
    "PackageSignature": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "packageId": {
          "type": "string"
        },
        "metadata": {
          "$ref": "#/$defs/PackageMetadata"
        },
        "typeDecls": {
          "$ref": "#/$defs/TypeDecls"
        },
        "interfaces": {
          "$ref": "#/$defs/Interfaces"
        }
      },
      "required": [
        "interfaces",
        "metadata",
        "packageId",
        "typeDecls"
      ]
    },
    "PackageMetadata": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "version"
      ]
    },
    "TypeDecls": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/TypeDecl"
      }
    },
    "TypeDecl": {
      "type": "object",
      "$comment": "Use oneOf with 2020-12 draft",
      "properties": {
        "Normal": {
          "$ref": "#/$defs/NormalTypeDecl"
        },
        "Template": {
          "$ref": "#/$defs/TemplateTypeDecl"
        }
      }
    },
    "TemplateTypeDecl": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "rec": {
          "$ref": "#/$defs/Record"
        },
        "template": {
          "$ref": "#/$defs/DefTemplate"
        }
      },
      "required": [
        "rec",
        "template"
      ]
    },
    "NormalTypeDecl": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "$ref": "#/$defs/DefDataType"
        }
      },
      "required": [
        "type"
      ]
    },
    "DefDataType": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "typeVars": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "dataType": {
          "$ref": "#/$defs/DataType"
        }
      },
      "required": [
        "dataType",
        "typeVars"
      ]
    },
    "DataType": {
      "type": "object",
      "$comment": "Use oneOf with 2020-12 draft",
      "properties": {
        "Enum": {
          "$ref": "#/$defs/Enum"
        },
        "Record": {
          "$ref": "#/$defs/Record"
        },
        "Variant": {
          "$ref": "#/$defs/Variant"
        }
      }
    },
    "Record": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "type": "array",
            "items": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "$ref": "#/$defs/Type"
              }
            ],
            "minItems": 2,
            "maxItems": 2
          }
        }
      },
      "required": [
        "fields"
      ]
    },
    "Field": {},
    "Enum": {
      "type": "object",
      "properties": {
        "constructors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "constructors"
      ]
    },
    "Variant": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "type": "array",
            "items": [
              {
                "type": "string"
              },
              {
                "type": "object",
                "$ref": "#/$defs/Type"
              }
            ],
            "minItems": 2,
            "maxItems": 2
          }
        }
      },
      "required": [
        "fields"
      ],
      "title": "Variant"
    },
    "Type": {
      "type": [ "object" ],
      "$comment": "Use oneOf with 2020-12 draft",
      "properties": {
        "TypeCon": {
          "$ref": "#/$defs/TypeCon"
        },
        "TypePrim": {
          "$ref": "#/$defs/TypePrim"
        },
        "TypeVar": {
          "$ref": "#/$defs/TypeVar"
        },
        "TypeNumeric": {
          "$ref": "#/$defs/TypeNumeric"
        }
      }
    },
    "TypeCon": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "typArgs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Type"
          }
        }
      },
      "required": [
        "name",
        "typArgs"
      ]
    },
    "TypePrim": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "typ": {
          "$ref": "#/$defs/PrimType"
        },
        "typArgs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Type"
          }
        }
      },
      "required": [
        "typ",
        "typArgs"
      ]
    },
    "TypeVar": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "TypeNumeric": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "scale": {
          "type": "integer"
        }
      },
      "required": [
        "scale"
      ]
    },
    "Template": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "rec": {
          "$ref": "#/$defs/Record"
        },
        "template": {
          "$ref": "#/$defs/DefTemplate"
        }
      },
      "required": [
        "rec",
        "template"
      ]
    },
    "DefTemplate": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "implementedInterfaces": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "key": {
          "$ref": "#/$defs/Type"
        },
        "tChoices": {
          "$ref": "#/$defs/TemplateChoices"
        }
      },
      "required": [
        "implementedInterfaces",
        "tChoices"
      ]
    },
    "PrimType": {
      "type": "string",
      "enum": [
        "PrimTypeParty",
        "PrimTypeBool",
        "PrimTypeInt64",
        "PrimTypeText",
        "PrimTypeDate",
        "PrimTypeTimestamp",
        "PrimTypeParty",
        "PrimTypeContractId",
        "PrimTypeList",
        "PrimTypeUnit",
        "PrimTypeOptional",
        "PrimTypeTextMap",
        "PrimTypeGenMap"
      ]
    },
    "TemplateChoices": {
      "type": "object",
      "$comment": "Use oneOf with 2020-12 draft",
      "properties": {
        "Resolved": {
          "$ref": "#/$defs/Resolved"
        },
        "Unresolved": {
          "$ref": "#/$defs/Unresolved"
        }
      }
    },
    "Resolved": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "resolvedChoices": {
          "type": "object",
          "$comment": "the key will be the interface name or 'none'",
          "additionalProperties": {
            "type": "object", 
            "additionalProperties": {
              "$ref": "#/$defs/TemplateChoice"
            }
          }
        }
      },
      "required": [
        "resolvedChoices"
      ]
    },
    "Unresolved": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "directChoices": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/TemplateChoice"
          }
        },
        "unresolvedChoiceSources": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "directChoices",
        "unresolvedChoiceSources"
      ]
    },
    "TemplateChoice": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "param": {
          "$ref": "#/$defs/Type"
        },
        "consuming": {
          "type": "boolean"
        },
        "returnType": {
          "$ref": "#/$defs/Type"
        }
      },
      "required": [
        "consuming",
        "param",
        "returnType"
      ]
    },
    "Interfaces": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/DefInterface"
      }
    },
    "DefInterface": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "choices": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/TemplateChoice"
          }
        },
        "viewType": {
          "type": "string"
        },
        "retroImplements": {
          "type": "array",
          "items": true
        }
      },
      "required": [
        "choices",
        "retroImplements",
        "viewType"
      ]
    }
  }
}

=== digital-asset/daml/sdk/type-json/example.json
{
  "packageId" : "2de5b3b4b7617d010bf515c1effefdde715d29343adb06c76630c9147a379390",
  "metadata" : {
    "name" : "ledger-tests-model",
    "version" : "1.0.0"
  },
  "typeDecls" : {
    "Stakeholders:ExplicitObservers" : {
      "Template" : {
        "rec" : {
          "fields" : [
            [
              "owner",
              {
                "TypePrim" : {
                  "typ" : "PrimTypeParty",
                  "typArgs" : [
                  ]
                }
              }
            ],
            [
              "thirdParty",
              {
                "TypePrim" : {
                  "typ" : "PrimTypeParty",
                  "typArgs" : [
                  ]
                }
              }
            ]
          ]
        },
        "template" : {
          "tChoices" : {
            "Resolved" : {
              "resolvedChoices" : {
                "Archive" : {
                  "none" : {
                    "param" : {
                      "TypeCon" : {
                        "name" : "9e70a8b3510d617f8a136213f33d6a903a10ca0eeec76bb06ba55d1ed9680f69:DA.Internal.Template:Archive",
                        "typArgs" : [
                        ]
                      }
                    },
                    "consuming" : true,
                    "returnType" : {
                      "TypePrim" : {
                        "typ" : "PrimTypeUnit",
                        "typArgs" : [
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "implementedInterfaces" : [
          ]
        }
      }
    },
    "AllTests:MPFetchOtherByKey" : {
      "Normal" : {
        "type" : {
          "typeVars" : [
          ],
          "dataType" : {
            "Record" : {
              "fields" : [
                [
                  "k1",
                  {
                    "TypePrim" : {
                      "typ" : "PrimTypeParty",
                      "typArgs" : [
                      ]
                    }
                  }
                ],
                [
                  "k2",
                  {
                    "TypePrim" : {
                      "typ" : "PrimTypeParty",
                      "typArgs" : [
                      ]
                    }
                  }
                ]
              ]
            }
          }
        }
      }
    },
    "Interfaces:ChildClone" : {
      "Template" : {
        "rec" : {
          "fields" : [
            [
              "party",
              {
                "TypePrim" : {
                  "typ" : "PrimTypeParty",
                  "typArgs" : [
                  ]
                }
              }
            ]
          ]
        },
        "template" : {
          "tChoices" : {
            "Unresolved" : {
              "directChoices" : {
                "Archive" : {
                  "param" : {
                    "TypeCon" : {
                      "name" : "9e70a8b3510d617f8a136213f33d6a903a10ca0eeec76bb06ba55d1ed9680f69:DA.Internal.Template:Archive",
                      "typArgs" : [
                      ]
                    }
                  },
                  "consuming" : true,
                  "returnType" : {
                    "TypePrim" : {
                      "typ" : "PrimTypeUnit",
                      "typArgs" : [
                      ]
                    }
                  }
                }
              },
              "unresolvedChoiceSources" : [
                "2de5b3b4b7617d010bf515c1effefdde715d29343adb06c76630c9147a379390:Interfaces:TIf"
              ]
            }
          },
          "implementedInterfaces" : [
            "2de5b3b4b7617d010bf515c1effefdde715d29343adb06c76630c9147a379390:Interfaces:TIf"
          ]
        }
      }
    },
    "Wolpertinger:Reproduce" : {
      "Normal" : {
        "type" : {
          "typeVars" : [
          ],
          "dataType" : {
            "Record" : {
              "fields" : [
                [
                  "mateId",
                  {
                    "TypePrim" : {
                      "typ" : "PrimTypeContractId",
                      "typArgs" : [
                        {
                          "TypeCon" : {
                            "name" : "2de5b3b4b7617d010bf515c1effefdde715d29343adb06c76630c9147a379390:Wolpertinger:Wolpertinger",
                            "typArgs" : [
                            ]
                          }
                        }
                      ]
                    }
                  }
                ],
                [
                  "tob",
                  {
                    "TypePrim" : {
                      "typ" : "PrimTypeTimestamp",
                      "typArgs" : [
                      ]
                    }
                  }
                ]
              ]
            }
          }
        }
      }
    },
    "Interfaces:Ham" : {
      "Normal" : {
        "type" : {
          "typeVars" : [
          ],
          "dataType" : {
            "Record" : {
              "fields" : [
              ]
            }
          }
        }
      }
    },
    "Wolpertinger:WolpertingerKey" : {
      "Normal" : {
        "type" : {
          "typeVars" : [
          ],
          "dataType" : {
            "Record" : {
              "fields" : [
                [
                  "owner",
                  {
                    "TypePrim" : {
                      "typ" : "PrimTypeParty",
                      "typArgs" : [
                      ]
                    }
                  }
                ],
                [
                  "age",
                  {
                    "TypeNumeric" : {
                      "scale" : 10
                    }
                  }
                ]
              ]
            }
          }
        }
      }
    },
    "AllTests:MultiParty" : {
      "Template" : {
        "rec" : {
          "fields" : [
            [
              "p1",
              {
                "TypePrim" : {
                  "typ" : "PrimTypeParty",
                  "typArgs" : [
                  ]
                }
              }
            ],
            [
              "p2",
              {
                "TypePrim" : {
                  "typ" : "PrimTypeParty",
                  "typArgs" : [
                  ]
                }
              }
            ]
          ]
        },
        "template" : {
          "tChoices" : {
            "Resolved" : {
              "resolvedChoices" : {
                "Archive" : {
                  "none" : {
                    "param" : {
                      "TypeCon" : {
                        "name" : "9e70a8b3510d617f8a136213f33d6a903a10ca0eeec76bb06ba55d1ed9680f69:DA.Internal.Template:Archive",
                        "typArgs" : [
                        ]
                      }
                    },
                    "consuming" : true,
                    "returnType" : {
                      "TypePrim" : {
                        "typ" : "PrimTypeUnit",
                        "typArgs" : [
                        ]
                      }
                    }
                  }
                },
                "MPFetchOtherByKey" : {
                  "none" : {
                    "param" : {
                      "TypeCon" : {
                        "name" : "2de5b3b4b7617d010bf515c1effefdde715d29343adb06c76630c9147a379390:AllTests:MPFetchOtherByKey",
                        "typArgs" : [
                        ]
                      }
                    },
                    "consuming" : false,
                    "returnType" : {
                      "TypePrim" : {
                        "typ" : "PrimTypeUnit",
                        "typArgs" : [
                        ]
                      }
                    }
                  }
                }
              }
            }
          },
          "key" : {
            "TypeCon" : {
              "name" : "5aee9b21b8e9a4c4975b5f4c4198e6e6e8469df49e2010820e792f393db870f4:DA.Types:Tuple2",
              "typArgs" : [
                {
                  "TypePrim" : {
                    "typ" : "PrimTypeParty",
                    "typArgs" : [
                    ]
                  }
                },
                {
                  "TypePrim" : {
                    "typ" : "PrimTypeParty",
                    "typArgs" : [
                    ]
                  }
                }
              ]
            }
          },
          "implementedInterfaces" : [
          ]
        }
      }
    },
    "Interfaces:Useless" : {
      "Normal" : {
        "type" : {
          "typeVars" : [
          ],
          "dataType" : {
            "Record" : {
              "fields" : [
                [
                  "interfacely",
                  {
                    "TypePrim" : {
                      "typ" : "PrimTypeContractId",
                      "typArgs" : [
                        {
                          "TypeCon" : {
                            "name" : "2de5b3b4b7617d010bf515c1effefdde715d29343adb06c76630c9147a379390:Interfaces:TIf",
                            "typArgs" : [
                            ]
                          }
                        }
                      ]
                    }
                  }
                ]
              ]
            }
          }
        }
      }
    },
    "Wolpertinger:Color.RGB" : {
      "Normal" : {
        "type" : {
          "typeVars" : [
          ],
          "dataType" : {
            "Record" : {
              "fields" : [
                [
                  "r",
                  {
                    "TypePrim" : {
                      "typ" : "PrimTypeInt64",
                      "typArgs" : [
                      ]
                    }
